In [2]:
import numpy as np

# basic operations

In [5]:
a = np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [6]:
a = np.array([1,2,3,4])
print(a+2)

[3 4 5 6]


In [7]:
print(a**2)

[ 1  4  9 16]


# All Arthmetic operation

In [10]:
b=np.ones(4)

In [12]:
print(b)

[1. 1. 1. 1.]


In [13]:
print(a+b)

[2. 3. 4. 5.]


In [14]:
c=np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [17]:
print(c*c)
print('*****************')
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [19]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a==b)

[False False False False]


In [20]:
print(a>b)

[False False False False]


In [21]:
print(a<b)

[ True  True  True  True]


In [23]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

False
True


# logical operators

In [26]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True False]
[ True False False False]


## Functions for creating array

In [3]:
a=np.arange(1,10,2)# give the jump values 
print(a)

[1 3 5 7 9]


In [4]:
a=np.linspace(0,1,5)# using display 5 values
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [5]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
a=np.eye(4,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [11]:
print(np.diag(a))

[1 2 3 4]


# Basic data types

In [12]:
a=np.arange(10)
print(a.dtype)

int64


In [13]:
a=np.arange(10)
print(a.dtype)

int64


In [14]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# other datatype

In [15]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [16]:
a=np.array([True,False])
print(a.dtype)

bool


In [17]:
a=np.array(["niha","Nihas"])
print(a.dtype) #unicode string type

<U5


# indexing and slicing

In [18]:
a=np.arange(10)
print(a[5])

5


In [19]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [20]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [21]:
a=np.arange(10)
print(a) 


[0 1 2 3 4 5 6 7 8 9]


In [22]:
print(a[1:8:2])

[1 3 5 7]


In [23]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# copies and viewing

In [25]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [26]:
print(np.shares_memory(a,b))

True


In [27]:
b[0]=10 #viewing
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [28]:
a=np.arange(10)
b=a[::2].copy() #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [29]:
print(np.shares_memory(a,b))

False


# Random number genarator

In [30]:
a=np.random.randint(0,20,15)
print(a)

[16  0  5  4  9 13  8 17 16  6 14 11 11 16  0]


In [31]:
mask=(a%2==0)

In [32]:
mask_a = a[mask]
print(mask_a)

[16  0  4  8 16  6 14 16  0]


In [33]:
a[mask]=-1
print(a)

[-1 -1  5 -1  9 13 -1 17 -1 -1 -1 11 11 -1 -1]
